services:
  ollama:
    command: 'serve'
    container_name: 'ollama'
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    volumes:
      - '.:/code'
      - './ollama:/root/.ollama'
