app:
    resource: classpath:./dashaun.pdf
spring:
    ai:
        ollama:
            base-url: http://${OLLAMA_HOST:localhost}:${OLLAMA_PORT:11434}
            chat:
                options:
                    model: llama3
    threads:
        virtual:
            enabled: true
